baseURL: "https://inirah02.github.io/harini.anand/" 
title: Harini Anand
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "I work at Niramai Health Analytix, a deep tech startup focusing on Breast Cancer, and used ML frameworks as a Research Intern at the Indian Institute of Technology Hyderabad, to predict gene regulatory networks. I have previously worked on building cognitive tools for reducing the onset of Dementia as a student entrepreneur. I led the largest technical community on campus, held workshops, and gave talks on Machine Learning, NLP, and Data Science. "
    author: Harini Anand
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Harini Anand
          subtitle: "I’m an enthusiastic undergraduate pursuing Computer Science interested in the fields of Computational Cognition, Machine Learning and Data Science. I want to delve deep into the intersection of Healthcare and AI. I’m also a curious creative writer, exploring different niches with my kaleidoscopic perspective."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Moritz-Maria von Igelfeld
          buttons:
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Data
              url: data/
            - name: Books
              url: books/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: cv
          url: cv.pdf
        - name: Email
          url: harini.anand@gmail.com
        - name: Zoom
          url: https://www.zoom.us/my/igelfeld
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=uSPqOjEAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/inirah02
        - name: Twitter
          url: https://twitter.com/anscombes4tet

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Harini Anand"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
